# CI\CD

trigger:
- az-pipelines

pool:
  name: Default

pr:
 branches:
   include:
     - main
# strategy:
#   matrix:
#     Python310:
#       python.version: '3.10'
#     Python311:
#       python.version: '3.11'
#     Python312:
#       python.version: '3.12'

stages:
  - stage: 'pyVersion'
    jobs:
      - job: 'pythonVersion'
        displayName: 'Run cmd'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
            displayName: 'Use python version'
          
          - script: |
              python --version
              py -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'
  
  - stage: 'archiveFile'
    jobs:
      - job : "Archivefile"
        displayName: 'Store a file'
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
            displayName: 'Archive files'

  - stage : 'publishArtifacts'
    jobs:
      - job: 'publishArtifacts'
        # displayName: 'Publish Artifacts'    
        steps:
        
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'Artifact 1'
            publishLocation: 'Container'
          displayName: 'publish buildArtifat'

          
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#     python --version
#   displayName: 'Run a multi-line script'
